# theme = "nord"
# theme = "autumn"
# theme = "sonokai"
theme = "default"


[editor]
true-color = true
color-modes = true
line-number = "relative"

# [editor.statusline]
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"

[editor.whitespace.render]
tab = "all"

# [editor.indent-guides]
# render = true
# character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[editor.cursor-shape]
insert = "bar"


# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
# C-s = ":w"
# F12 = ":open ~/.config/helix/config.toml" # Maps the Ctrl-o to opening of the helix config file
F12 = ":config-open"
# "ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
"р" = "move_char_left"
"о" = "move_line_down"
"л" = "move_line_up"
"д" = "move_char_right"
F5 = [":w", ":sh tmux send-keys -t .2 Up Enter"]

[keys.normal.space]
"space" = "command_palette"
c = "toggle_comments"
q = ":q"
ret = ":w"

[keys.insert.j]
j = "normal_mode"
# j = ":insert-output printf 'j'"
